/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTrustLedgerRouteImport } from './routes/_app.trust-ledger'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppOffersRouteImport } from './routes/_app.offers'
import { Route as AppMoneyMoodRouteImport } from './routes/_app.money-mood'
import { Route as AppLifeEventsRouteImport } from './routes/_app.life-events'
import { Route as AppFinancesRouteImport } from './routes/_app.finances'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAiAdvisorRouteImport } from './routes/_app.ai-advisor'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrustLedgerRoute = AppTrustLedgerRouteImport.update({
  id: '/trust-ledger',
  path: '/trust-ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersRoute = AppOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyMoodRoute = AppMoneyMoodRouteImport.update({
  id: '/money-mood',
  path: '/money-mood',
  getParentRoute: () => AppRoute,
} as any)
const AppLifeEventsRoute = AppLifeEventsRouteImport.update({
  id: '/life-events',
  path: '/life-events',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesRoute = AppFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAdvisorRoute = AppAiAdvisorRouteImport.update({
  id: '/ai-advisor',
  path: '/ai-advisor',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-advisor': typeof AppAiAdvisorRoute
  '/dashboard': typeof AppDashboardRoute
  '/finances': typeof AppFinancesRoute
  '/life-events': typeof AppLifeEventsRoute
  '/money-mood': typeof AppMoneyMoodRoute
  '/offers': typeof AppOffersRoute
  '/settings': typeof AppSettingsRoute
  '/trust-ledger': typeof AppTrustLedgerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-advisor': typeof AppAiAdvisorRoute
  '/dashboard': typeof AppDashboardRoute
  '/finances': typeof AppFinancesRoute
  '/life-events': typeof AppLifeEventsRoute
  '/money-mood': typeof AppMoneyMoodRoute
  '/offers': typeof AppOffersRoute
  '/settings': typeof AppSettingsRoute
  '/trust-ledger': typeof AppTrustLedgerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/ai-advisor': typeof AppAiAdvisorRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/finances': typeof AppFinancesRoute
  '/_app/life-events': typeof AppLifeEventsRoute
  '/_app/money-mood': typeof AppMoneyMoodRoute
  '/_app/offers': typeof AppOffersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/trust-ledger': typeof AppTrustLedgerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-advisor'
    | '/dashboard'
    | '/finances'
    | '/life-events'
    | '/money-mood'
    | '/offers'
    | '/settings'
    | '/trust-ledger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ai-advisor'
    | '/dashboard'
    | '/finances'
    | '/life-events'
    | '/money-mood'
    | '/offers'
    | '/settings'
    | '/trust-ledger'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/ai-advisor'
    | '/_app/dashboard'
    | '/_app/finances'
    | '/_app/life-events'
    | '/_app/money-mood'
    | '/_app/offers'
    | '/_app/settings'
    | '/_app/trust-ledger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trust-ledger': {
      id: '/_app/trust-ledger'
      path: '/trust-ledger'
      fullPath: '/trust-ledger'
      preLoaderRoute: typeof AppTrustLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offers': {
      id: '/_app/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AppOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/money-mood': {
      id: '/_app/money-mood'
      path: '/money-mood'
      fullPath: '/money-mood'
      preLoaderRoute: typeof AppMoneyMoodRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/life-events': {
      id: '/_app/life-events'
      path: '/life-events'
      fullPath: '/life-events'
      preLoaderRoute: typeof AppLifeEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finances': {
      id: '/_app/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AppFinancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-advisor': {
      id: '/_app/ai-advisor'
      path: '/ai-advisor'
      fullPath: '/ai-advisor'
      preLoaderRoute: typeof AppAiAdvisorRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiAdvisorRoute: typeof AppAiAdvisorRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinancesRoute: typeof AppFinancesRoute
  AppLifeEventsRoute: typeof AppLifeEventsRoute
  AppMoneyMoodRoute: typeof AppMoneyMoodRoute
  AppOffersRoute: typeof AppOffersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTrustLedgerRoute: typeof AppTrustLedgerRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiAdvisorRoute: AppAiAdvisorRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinancesRoute: AppFinancesRoute,
  AppLifeEventsRoute: AppLifeEventsRoute,
  AppMoneyMoodRoute: AppMoneyMoodRoute,
  AppOffersRoute: AppOffersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTrustLedgerRoute: AppTrustLedgerRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
